### ISSUE TITLE
WritingTool nightly doesn't work — 2024-10-26

### ISSUE THREAD

**Issue by marcoagpinto** [writingtool-org/writingtool#14]
Heya, @FredKruse 

The nightly no longer works.

Not even the settings and “about window” appear.

**Comment by FredKruse** [comment]
Heya Marco,
Since the last two snapshots, WritingTool requires Java version 17 or higher. LanguageTool has updated to this version and forced me to upgrade as well. I will publish this on the WritingTool site.

**Comment by marcoagpinto** [comment]
Ahhhh… it worked with Java 17.

Thanks!
