### ISSUE TITLE
Error Message when typing

### ISSUE THREAD

**Issue by GerryT11** [writingtool-org/writingtool#15]
I've got this error message when typing (new document, error came after a few lines)
System: WritingTool 1.0, LibreOffice 24.2.6.2 (X86_64), Ubuntu 24.4

![Screenshot from 2024-11-08 12-49-04](https://github.com/user-attachments/assets/8d484dec-c3e6-49bb-8572-7ae3672d20e6)

**Comment by FredKruse** [comment]
This issue has the same cause as issue #6.
I fixed it.
Please test it with tomorrow's snapshot (https://writingtool.org/writingtool/snapshots/)

**Comment by GerryT11** [comment]
Thank you for fixing it! The bug did not reappear so far. I close the bug and also bug 6.
