### ISSUE TITLE
Error message while opening a spreadsheet 

### ISSUE THREAD

**Issue by GerryT11** [writingtool-org/writingtool#16]
I've got this error message while opening a spreadsheet file.
System: Ubuntu 24.4, LibreOffice 24.2, WritingTool Snapshot 15.11.2024
![Screenshot from 2024-11-22 17-59-30](https://github.com/user-attachments/assets/e3948f65-823b-4a14-82b7-0ad83bfd8cc3)

**Comment by FredKruse** [comment]
see issue #18

**Comment by GerryT11** [comment]
I've uninstalled and then reinstalled the latest snapshot. So far no error messages. I close this and bug 18. Thank you!
