### ISSUE TITLE
Error messages while opening files and changing the language

### ISSUE THREAD

**Issue by GerryT11** [writingtool-org/writingtool#18]
Error messages while opening LibreOffice files and changing the language of the paragraph style.
System: Ubuntu 24.4 and LibreOffice 24.2, WritingTool Snapshot 15.11.2024

![Screenshot from 2024-11-25 12-34-49](https://github.com/user-attachments/assets/0a9a96e8-0ba4-43f5-a55e-1d8b63d64588)
![Screenshot from 2024-11-25 12-32-53](https://github.com/user-attachments/assets/8d7c1d47-f10e-4d54-be5f-01ad744ab1e9)

**Comment by GerryT11** [comment]
Another error message on same action: Opening a Writer file (1 page long, in German language).

![Screenshot from 2024-11-26 16-33-24](https://github.com/user-attachments/assets/3c2174df-a6b1-4a32-8ff7-67a0ec334b7c)

**Comment by GerryT11** [comment]
Thank you for looking into this bug. 

Here some details about my installation:
- My system is an Ubuntu 24.4 (Ubuntu 24.04.1 LTS) on an Lenovo Thinkpad E16 GEn1 AMD. It is a fresh installation, also the LibreOffice profile was new/clean. 
- LibreOffice uses the following Java runtime environment "Vendor Ubuntu, Version 21.0.5, java-21-openjdk-amd64"
- I installed WritingTool from the snapshot folder. The bug occurred on snapshot 15.11.2024.
- LibreOffice Version: 24.2.6.2 (X86_64) / LibreOffice Community;
Build ID: 420(Build:2)
CPU threads: 16; OS: Linux 6.8; UI render: default; VCL: gtk3
Locale: en-CA (en_CA.UTF-8); UI: en-US
Ubuntu package version: 4:24.2.6-0ubuntu0.24.04.1
Calc: threaded

Do you need any other information on the installation?

**Comment by FredKruse** [comment]
I installed a new Ubuntu 24.4 and a new LibreOffice in it. I then installed the WritingTool snapshot from November 15, 2024. Everything works perfectly.
Something must have gone wrong with your installation. It doesn't find a spell checker class that comes from LT and is always included. Please uninstall the current version of WT and reinstall the latest snapshot.
Please let me know if it worked.

**Comment by GerryT11** [comment]
I've uninstalled and then reinstalled the latest snapshot. So far no error messages. I close this and bug 16. Thank you!
