### ISSUE TITLE
WritingTool Spellchecker Marking All Possessives as Incorrect

### ISSUE THREAD

**Issue by DialecticalPersuasion** [writingtool-org/writingtool#19]
Not sure if I accidentally hit a wrong setting at some point, but the spellchecker has been marking all possessive nouns as incorrectly spelled. This has been happening for as long as I can remember using the extension. Changing the spellchecker back to the LO default Hunspell SpellChecker fixes the problem. If anyone knows anything about this issue, that would be appreciative. Thanks for your time.

![soffice bin_ACt1GUJ2me](https://github.com/user-attachments/assets/efb99b00-8ce1-43c0-8a97-38443703f03a)

**Comment by FredKruse** [comment]
@DialecticalPersuasion 
What language do you use? Could you post an example text, to illustrate the problem?

**Comment by DialecticalPersuasion** [comment]
@FredKruse 
I use American English. Here is a comparison between the default Hunspell Spellchecker (first) and WritingTool (second).
![pO8TVm8IkP](https://github.com/user-attachments/assets/b8a8e974-aece-4252-8d9a-d86917d083f9)
![soffice bin_7PGxYp0n5b](https://github.com/user-attachments/assets/6c02c618-37b7-49b8-939a-dd2317c5f577)

**Comment by FredKruse** [comment]
The problem should be solved. Please test it with tomorrows nightly and give me feedback.

**Comment by DialecticalPersuasion** [comment]
I'm sorry, I'm not very well versed with this kind of file management. How and where do I install or update the extension with these new fixes?

**Comment by FredKruse** [comment]
You find Here the last updates: https://writingtool.org/writingtool/snapshots/

**Comment by DialecticalPersuasion** [comment]
Ok, I added the snapshot via the extension menu, but the whole extension seems to have stopped working. I captured a screen recording to show what's changed.

https://github.com/user-attachments/assets/5b528d33-5aa7-46b2-9a1d-1739cf8fa861

**Comment by FredKruse** [comment]
Have you activated the correct Java Runtime Environment (JRE)? You can find it at the menu: Tools/Options/LibreOffice/Advanced/Java Options.
The checkbox must be checked and the correct JRE (17 or higher) must be selected.
Please let me know if this solves the problem.

**Comment by DialecticalPersuasion** [comment]
Just checked and yes I was using Eclipse Temurin. Switched to the Oracle JRE and everything runs perfect now. The snapshot works and possessives are fixed! Thank you for all your help!
