### ISSUE TITLE
No nightly for three days — 2024-09-14

### ISSUE THREAD

**Issue by marcoagpinto** [writingtool-org/writingtool#2]
Heya, @FredKruse ,

I have updated the bottom of my website with the new URLs of WritingTool:
https://proofingtoolgui.org/getting_involved.html

I visited the nightlies page:
https://writingtool.org/writingtool/snapshots

And for some three days that there is no nightly.

Thanks!

**Comment by FredKruse** [comment]
Heya, @marcoagpinto,
it was a problem as a result of the switch of domain. I copied the last snapshots per hand.
Hopefully, the automatic generation will run now.
Thanks for testing.
