### ISSUE TITLE
No nightlies — 2024-12-08

### ISSUE THREAD

**Issue by marcoagpinto** [writingtool-org/writingtool#24]
Heya, @FredKruse 

The last nightly is dated from 4-DEC.

Is the building script broken?

Thanks!

**Comment by FredKruse** [comment]
Heya, @marcoagpinto 
Thanks for the watching the snapshots.
It seems that my technical environment is not so stable. Unfortunately, this is not a professional project. I got everything back in order. However, the second to last snapshot was lost.
