### ISSUE TITLE
Greek spell check on libre office suggests incorrect capitalizations

### ISSUE THREAD

**Issue by vassijoseph** [writingtool-org/writingtool#27]
When using the spell check in libre office the Greek spell check suggests to capitalize the first letter of a word if the word is followed by a full stop or an exclamation point 

For example the text 
Γεια σου κοσμε. (Missing intonation on κόσμε)

When using spell check all suggestions have the first letter capitalized
Γεια σου Κόσμε.
Which is incorrect

It should be 
Γεια σου κόσμε.

The same happens with an exclamation point
Γεια σου κοσμε!
But not with any other punctuation points as far as I could tell

It also doesn't occur at least in English, I don't know about other languages

Sorry if this bug report is badly structured I had to use my phone to post it

**Comment by vassijoseph** [comment]
Sorry I forgot I provided zero info about my system
I am on Linux Mint 22 xfce
Linux kernel 6.8

Libre office version  24.2.7.2 (X86_64) Build ID: 420(Build:2)
When I reported this I was using the Writing tool available at the libreoffice extensions site
https://extensions.libreoffice.org/en/extensions/show/99240

I used the latest from the link you provided "WritingTool_2024-12-14-snapshot" and the problem persists
![Screenshot_2024-12-15_15-54-25](https://github.com/user-attachments/assets/c58e6e79-5a0b-488f-a426-91c80c0bb47f)
![Screenshot_2024-12-15_15-54-55](https://github.com/user-attachments/assets/5fc3af55-f3e2-46c5-adab-1f594e367e84)

**Comment by FredKruse** [comment]
I tried to reproduce the problem. I also work under Linux Mint but with LibreOffice 24.8.3.2. The application works correctly there.
![spell](https://github.com/user-attachments/assets/4f330e37-76e6-44b6-aa2b-313d546489c9)

Could you deactivate the WritingTool spell checker? Under Tools/Options/Languages ​​and Locales/Writing Aids/Available Language Models, click the Edit button and deactivate the WritingTool checkbox under Spelling.
Please test what happens then with the spell checking.

**Comment by vassijoseph** [comment]
I installed the libre office available on flatpak which was a newer version, possibly the one you mentioned and it worked correctly

It seems like the default libre office available on linux mints package manager is outdated
