### ISSUE TITLE
Temporarily disabled rules not working for subrules — 2024-09-15

### ISSUE THREAD

**Issue by marcoagpinto** [writingtool-org/writingtool#3]
Heya, @FredKruse ,

Yesterday, I created a pt-PT specific rule:

```
        <rulegroup id='INFORMALITIES' name="[pt-PT] Linguagem informal" default="on" tags="picky" tone_tags="formal">

blah blah blah
blah blah

    <rule default='temp_off'>
        <pattern>
            <token>à</token>
            <token>coisa</token>
            <token>de</token>
        </pattern>
        <message>Esta é uma expressão oral. Reveja.</message>
        <short>Coloquialismo</short>
        <example correction=''><marker>à coisa de</marker></example>
    </rule>
</rulegroup>
```

This morning I downloaded the latest nightly and typed in LibreOffice 28.8.1.2:
```
Isto aconteceu à coisa de dois minutos.
E para ver se.
```

But it doesn't trigger: “à coisa de”.

Thanks!

**Comment by FredKruse** [comment]
There was another problem in generating the automatic snapshots (because of changing the domain). It should be solved now.
I changed the last snapshot manually. Please test it.

**Comment by marcoagpinto** [comment]
It is working, @FredKruse !

And it also fixed the issue that I tried to disable the long sentences rule with a right-click and it did nothing.

Thank you!
