### ISSUE TITLE
WritingTool error message while deleting empty line.

### ISSUE THREAD

**Issue by GerryT11** [writingtool-org/writingtool#6]
The following error message occurred while typing. At this moment, I was deleting an empty line (including a paragraph break). The error occurred once and I could not reproduce the error afterwards.

![Screenshot from 2024-09-19 06-15-15](https://github.com/user-attachments/assets/add256ec-d33c-4b71-8ebc-76122be2a734)

**Comment by FredKruse** [comment]
see issue #15

**Comment by GerryT11** [comment]
Thank you for fixing it! The bug did not reappear so far. I close the bug and also bug 15.
